In [112]:
import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [181]:
data=pd.read_csv(r'C:\Users\USER\Final model.csv')

In [178]:
data['Gender']=data['Gender'].str.upper()

In [180]:
data.to_csv('Final model.csv',index=False)

In [182]:
data.head()

Gender  Time(hours)  Previous cycle  No of stooling per day  \
0    MALE         72.0             NaN                     5.0   
1  FEMALE         72.0             NaN                     8.0   
2    MALE          NaN             NaN                     NaN   
3  FEMALE         24.0            28.0                     NaN   
4    MALE          NaN             NaN                     NaN   

                Symptom 1            Symptom 2         Symptom 3  \
0          ABDOMINAL PAIN      ABDOMINAL PAINS     WATERY FAECES   
1          BLOOD IN STOOL  PERSISTENT VOMITING     STOMACHE ACHE   
2                   FEVER             HEADACHE            NAUSEA   
3  BLOOD FLOW FROM VAGINA          MOOD SWINGS  TROUBLE SLEEPING   
4                   FEVER             HEADACHE            NAUSEA   

       Symptom 4                Symptom 5           Symptom 6  \
0         NAUSEA                 VOMITING                 NaN   
1    WEIGHT LOSS              DEHYDRATION                 NaN   
2         CHILLS                   CHILLS  EXCESSIVE SWEATING   
3  FOOD CRAVINGS  CRAMPS IN LOWER ABDOMEN                 NaN   
4         CHILLS                   CHILLS  EXCESSIVE SWEATING   

              Symptom 7                 Symptom 8          Symptom 9  \
0                   NaN                       NaN                NaN   
1                   NaN                       NaN                NaN   
2              DIARRHEA  GENERALLY FEELING UNWELL            ANAEMIA   
3  CRAMPS IN LOWER BACK                  BLOATING  BREAST TENDERNESS   
4              DIARRHEA  GENERALLY FEELING UNWELL            ANAEMIA   

  Symptom 10 Symptom 11 Symptom 12 Symptom 13     Diagnosis  
0        NaN        NaN        NaN        NaN      DIARRHEA  
1        NaN        NaN        NaN        NaN      DIARRHEA  
2        NaN        NaN        NaN        NaN       MALARIA  
3       ACNE        NaN        NaN        NaN  MENSTURATION  
4        NaN        NaN        NaN        NaN       MALARIA

In [116]:
from sklearn.preprocessing import LabelEncoder

In [117]:
cl= ['Gender', 'Time(hours)', 'Previous cycle', 'No of stooling per day',
       'Symptom 1', 'Symptom 2', 'Symptom 3', 'Symptom 4', 'Symptom 5',
       'Symptom 6', 'Symptom 7', 'Symptom 8', 'Symptom 9', 'Symptom 10',
       'Symptom 11', 'Symptom 12', 'Symptom 13', 'Diagnosis']
encoder=LabelEncoder()
data[cl]=data[cl].apply(encoder.fit_transform)

In [126]:
x=data.drop('Diagnosis',axis=1)
y=data['Diagnosis']

In [129]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
y_train=keras.utils.to_categorical(y_train,num_classes=3)
y_test=keras.utils.to_categorical(y_test,num_classes=3)

In [132]:
encoder=LabelEncoder()
x=np.array(x).ravel()
encoder.fit(x)
np.save('classes.npy',encoder.classes_)

In [130]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras import backend as K
model=Sequential()
model.add(Dense(64,activation="relu",input_dim=17))
model.add(Dropout(0.5))
model.add(Dense(64,activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(3,activation="softmax"))
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss="categorical_crossentropy",metrics=["accuracy"])
model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test),shuffle=True)

Epoch 1/100
25/25 [==============================] - 1s 18ms/step - loss: 4.3604 - accuracy: 0.3900 - val_loss: 1.1612 - val_accuracy: 0.5900
Epoch 2/100
25/25 [==============================] - 0s 5ms/step - loss: 2.5391 - accuracy: 0.3950 - val_loss: 0.6921 - val_accuracy: 0.7250
Epoch 3/100
25/25 [==============================] - 0s 4ms/step - loss: 1.7500 - accuracy: 0.4963 - val_loss: 0.5989 - val_accuracy: 0.8250
Epoch 4/100
25/25 [==============================] - 0s 4ms/step - loss: 1.2716 - accuracy: 0.5688 - val_loss: 0.5432 - val_accuracy: 0.8250
Epoch 5/100
25/25 [==============================] - 0s 5ms/step - loss: 1.0113 - accuracy: 0.6012 - val_loss: 0.4974 - val_accuracy: 0.7700
Epoch 6/100
25/25 [==============================] - 0s 5ms/step - loss: 0.8624 - accuracy: 0.6463 - val_loss: 0.4669 - val_accuracy: 0.8550
Epoch 7/100
25/25 [==============================] - 0s 5ms/step - loss: 0.7966 - accuracy: 0.6700 - val_loss: 0.4334 - val_accuracy: 0.9000
Epoch 8/100


In [133]:
save_path="./final_model.h5"
model.save(save_path)
model=keras.models.load_model(save_path)

In [134]:
from keras.models import load_model
model= load_model(r"C:\Users\USER\Desktop\Web Apps\Diagnosis app\final_model.h5")

In [135]:
val=['female',72,0,8,'BLOOD IN STOOL','PERSISTENT VOMITING','STOMACHE ACHE','WEIGHT LOSS','DEHYDRATION',100,100,100,100,100,100,100,100]
final=[]
for v in val:
    if type(v)==str:
        v=v.upper()
        final.append(v)
    else:
        final.append(v)
        

In [163]:
encoder=LabelEncoder()
encoder.classes_=np.load('classes.npy',allow_pickle=True)

In [164]:
encoder.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18], dtype=int64)

In [165]:
x=encoder.fit_transform(final)

In [166]:
x=np.array(x).reshape(1,17)

In [167]:
x=model.predict(x)

1/1 [==============================] - 0s 23ms/step


In [168]:
x

array([[0.99396956, 0.00193065, 0.00409972]], dtype=float32)

In [172]:
clas=np.argmax(x,axis=1)
if clas == 0:
    clas='Diarrhea'
elif clas == 1:
    clas='Malaria'
else:
    clas=='Mensturation'

In [173]:
print('Diagnosis is',(x[0,0]*100).round(2),'%',clas)

Diagnosis is 99.4 % Diarrhea


In [143]:
x

array([0], dtype=int64)